version: "3"
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`in-x.com`)"
